services:
  crafty:
    container_name: crafty-controller
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    environment:
        - TZ=Europe/Paris
    ports:
        - "8443:8443" # HTTPS
        #- "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - /docker/appdata/crafty-controller/backups:/crafty/backups
        - /docker/appdata/crafty-controller/logs:/crafty/logs
        - /docker/appdata/crafty-controller/servers:/crafty/servers
        - /docker/appdata/crafty-controller/config:/crafty/app/config
        - /docker/appdata/crafty-controller/import:/crafty/import